/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/images/models/environment.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/environment.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.sand} position={[-53.705, 0, -51.512]} rotation={[0, 0.883, 0]} scale={[182.556, 17.701, 144.595]} />
      <mesh geometry={nodes.phonescreen.geometry} material={materials['Black Screen']} position={[-88.15, 5.86, -90.755]} scale={[1.866, 1.153, 1.866]} />
      <group position={[52.453, 71.284, -282.094]} rotation={[3.122, 0.808, 3.14]} scale={[18.048, 54.958, 18.048]}>
        <mesh geometry={nodes.Cube023.geometry} material={materials['Black Screen']} />
        <mesh geometry={nodes.Cube023_1.geometry} material={materials['Phone case']} />
      </group>
      <group position={[52.453, 71.284, -282.094]} rotation={[3.122, 0.808, 3.14]} scale={[18.048, 54.958, 18.048]}>
        <mesh geometry={nodes.Cube086.geometry} material={materials['WhiteMarble.006']} />
        <mesh geometry={nodes.Cube086_1.geometry} material={materials['copper.006']} />
        <mesh geometry={nodes.Cube086_2.geometry} material={materials['darkCopper.002']} />
        <mesh geometry={nodes.Cube086_3.geometry} material={materials['copper.007']} />
        <mesh geometry={nodes.Cube086_4.geometry} material={materials['copper.008']} />
      </group>
      <mesh geometry={nodes.laptopscreen.geometry} material={materials['Black Screen']} position={[-68.498, 9.075, -51.007]} rotation={[1.508, 0.163, -1.199]} scale={[-3.413, -0.085, -2.526]} />
      <group position={[-68.498, 9.075, -51.007]} rotation={[1.486, 0.153, -1.061]} scale={[-3.413, -0.085, -2.526]}>
        <mesh geometry={nodes.Cube077.geometry} material={materials['WhiteMarble.005']} />
        <mesh geometry={nodes.Cube077_1.geometry} material={materials['copper.003']} />
        <mesh geometry={nodes.Cube077_2.geometry} material={materials['darkCopper.001']} />
        <mesh geometry={nodes.Cube077_3.geometry} material={materials['copper.004']} />
      </group>
      <group position={[-68.604, 9.075, -51.037]} rotation={[1.481, 0.229, -1.192]} scale={[-3.413, -0.085, -2.526]}>
        <mesh geometry={nodes.Cube076.geometry} material={materials.white} />
        <mesh geometry={nodes.Cube076_1.geometry} material={materials['grey keyboard']} />
      </group>
      <group position={[-44.129, 4.932, -9.277]} rotation={[0, 1.176, 0]} scale={[1.23, 0.686, 1.23]}>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials.WhiteMarble} />
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['WhiteMarble.001']} />
        <mesh geometry={nodes.Cylinder004_2.geometry} material={materials['WhiteMarble.002']} />
        <mesh geometry={nodes.Cylinder004_3.geometry} material={materials['WhiteMarble.003']} />
        <mesh geometry={nodes.Cylinder004_4.geometry} material={materials['copper.001']} />
        <mesh geometry={nodes.Cylinder004_5.geometry} material={materials['copper.002']} />
      </group>
      <group position={[-33.589, 5.86, -41.283]} rotation={[0, 0.087, 0]} scale={[1.23, 0.76, 1.23]}>
        <mesh geometry={nodes.Cylinder014.geometry} material={materials.white} />
        <mesh geometry={nodes.Cylinder014_1.geometry} material={materials['Black Screen']} />
        <mesh geometry={nodes.Cylinder014_2.geometry} material={materials.glass} />
        <mesh geometry={nodes.Cylinder014_3.geometry} material={materials.payment} />
        <mesh geometry={nodes.Cylinder014_4.geometry} material={materials['grey keyboard']} />
      </group>
      <mesh geometry={nodes.vendingscreen.geometry} material={materials['Black Screen']} position={[-33.589, 5.86, -41.283]} rotation={[0, 0.087, 0]} scale={[1.23, 0.76, 1.23]} />
      <group position={[-5.98, 6.309, 14.263]} rotation={[0, 1.27, 0]} scale={[0.959, 0.834, 0.959]}>
        <mesh geometry={nodes.Sphere.geometry} material={materials.antena} />
        <mesh geometry={nodes.Sphere_1.geometry} material={materials.wood} />
        <mesh geometry={nodes.Sphere_2.geometry} material={materials.tvbutton} />
        <mesh geometry={nodes.Sphere_3.geometry} material={materials.tvfolds} />
        <mesh geometry={nodes.Sphere_4.geometry} material={materials.metaltvframe} />
      </group>
      <mesh geometry={nodes.tvscreen001.geometry} material={materials['Black Screen']} position={[-5.98, 6.309, 14.263]} rotation={[0, 1.27, 0]} scale={[0.959, 0.834, 0.959]} />
      <group position={[-5.98, 6.309, 14.263]} rotation={[0, 1.27, 0]} scale={[0.959, 0.834, 0.959]}>
        <mesh geometry={nodes.Sphere023.geometry} material={materials['WhiteMarble.007']} />
        <mesh geometry={nodes.Sphere023_1.geometry} material={materials['copper.010']} />
        <mesh geometry={nodes.Sphere023_2.geometry} material={materials['darkCopper.003']} />
        <mesh geometry={nodes.Sphere023_3.geometry} material={materials['copper.011']} />
        <mesh geometry={nodes.Sphere023_4.geometry} material={materials['WhiteMarble.008']} />
      </group>
      <mesh geometry={nodes.bg.geometry} material={materials['WhiteMarble.006']} position={[52.453, 115.709, -282.094]} rotation={[3.122, 0.808, 3.14]} scale={[18.051, 97.405, 18.051]} />
    </group>
  )
}

useGLTF.preload('/environment.glb')
